package com.company;

public enum State {
    INITIAL,
    SINGLE_ZERO,
    DECIMAL_NUMBER,
    SINGLE_PLUS,
    SINGLE_MINUS,
    SOME_OPERATOR_BEFORE_EQUAL,
    SINGLE_LESS,
    SINGLE_GREATER,
    SINGLE_SLASH,
    SINGLE_AMPERSAND,
    SINGLE_VERTICAL_BAR,
    SINGLE_COLON,
    IDENTIFIER,
    SINGLE_DOT,
    SYMBOLIC_CONSTANT,
    LITERAL_CONSTANT,
    MULTI_LINE_COMMENT,
    SINGLE_LINE_COMMENT,
    STAR_IN_MULTI_LINE_COMMENT
}
